save_data: /home/lgm/VRepair/param_sweep/17_parameter_sweep/data
overwrite: false
n_sample: -1
src_vocab_size: 10000
tgt_vocab_size: 10000
src_seq_length: 1000
tgt_seq_length: 100
data:
  github:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
  valid:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
seed: 0
learning_rate: 0.0001
rnn_size: 1024
word_vec_size: 1024
