save_data: /home/lgm/VRepair2.0/param_sweep_tgt/00_parameter_sweep/data
src_vocab: /home/lgm/VRepair2.0/param_sweep_tgt/00_parameter_sweep/data.vocab.src
tgt_vocab: /home/lgm/VRepair2.0/param_sweep_tgt/00_parameter_sweep/data.vocab.tgt
overwrite: false
n_sample: -1
data:
  github:
    path_src: /home/lgm/VRepair2.0/vul_data/random_fine_tune_train.src.txt
    path_tgt: /home/lgm/VRepair2.0/vul_data/random_fine_tune_train.tgt.txt
  valid:
    path_src: /home/lgm/VRepair2.0/vul_data/random_fine_tune_valid.src.txt
    path_tgt: /home/lgm/VRepair2.0/vul_data/random_fine_tune_valid.tgt.txt
seed: 0
