save_data: /home/lgm/VRepair/param_sweep/0_parameter_sweep/data
src_vocab: /home/lgm/VRepair/param_sweep/0_parameter_sweep/data.vocab.src
tgt_vocab: /home/lgm/VRepair/param_sweep/0_parameter_sweep/data.vocab.tgt
overwrite: false
n_sample: -1
src_vocab_size: 2000
tgt_vocab_size: 2000
src_seq_length: 1000
tgt_seq_length: 100
data:
  github:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
    transforms: [filtertoolong]
  valid:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
    transforms: [filtertoolong]
seed: 0
learning_rate: 0.0005
rnn_size: 256
word_vec_size: 256
