save_data: /home/lgm/VRepair/param_sweep/18_parameter_sweep/data
overwrite: false
n_sample: -1
src_vocab_size: 2000
tgt_vocab_size: 2000
src_seq_length: 1000
tgt_seq_length: 100
data:
  github:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
  valid:
    path_src: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.src.txt
    path_tgt: /home/lgm/VRepair/data/Context10/BugFixTokenPairs_commits.tgt.txt
seed: 0
learning_rate: 5.0e-05
rnn_size: 256
word_vec_size: 256
